apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emergency-response.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emergency-response.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.app.secrets.secretKey | b64enc | quote }}
  database-password: {{ .Values.app.secrets.databasePassword | b64enc | quote }}
